{
 "title": "AUSD Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Health Factor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ausd_average_health_factor", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Backing Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ausd_backing_percentage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Users active",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ausd_active_users_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Supply",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ausd_total_supply", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Users at Ristk",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ausd_users_at_risk", "legendFormat": "__auto" }
   ]
  },
  { "title": "Liquidations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Liquidatable Users",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ausd_liquidatable_users", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Liquidated Debt",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ausd_liquidated_debt_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Liquidations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ausd_liquidations_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "Collateral", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Collaterization ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ausd_collateralization_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Token Price USD",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expr": "ausd_token_price_usd", "legendFormat": "__auto" }
   ]
  },
  { "title": "AUSD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Total amount burned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ausd_burned_amount_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total burns",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ausd_burns_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Amount Minted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ausd_minted_amount_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Mints",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ausd_mints_total", "legendFormat": "__auto" }
   ]
  }
 ]
}