{
 "title": "AUSD Backend Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "< 100ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(ausd_http_request_duration_seconds_bucket{le=\"0.1\"}[5m]))\r\n/\r\n  sum(rate(ausd_http_request_duration_seconds_count[5m]))\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Cache Misses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ausd_cache_misses_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Cache Hits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ausd_cache_hits_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "group by(endpoint, method, instance, __name__) (ausd_http_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, endpoint) (\r\n    rate(ausd_http_request_duration_seconds_bucket[5m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}